# Generated by Django 4.0 on 2021-12-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0003_alter_schemacolumnmodel_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafile',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_files', to='data_generator.schema'),
        ),
    ]
