# Generated by Django 4.0 on 2022-01-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0004_alter_schemafile_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Files with data'),
        ),
    ]
